name: iOSEngineerCodeCheck
options:
  bundleIdPrefix: jp.yumemi.iOSEngineerCodeCheck
  deploymentTarget:
    iOS: 15.0
  generateEmptyDirectories: true
  
fileGroups:
  - project.yml
  - README.md
  - .swiftlint.yml
  - Dangerfile.swift

targets:
  iOSEngineerCodeCheck:
    platform: iOS
    type: application
    sources:
      - iOSEngineerCodeCheck/
    postBuildScripts:
      - name: swiftlint
        script: |
                if which swiftlint >/dev/null; then
                    swiftlint autocorrect --format
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
  iOSEngineerCodeCheckTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - iOSEngineerCodeCheckTests/
      
    dependencies:
      - target: iOSEngineerCodeCheck

    scheme:
      testTargets:
        - iOSEngineerCodeCheckTests

