name: SwiftLint

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Danger Swift
        uses: danger/swift@2.0.3

